Django3.2対応
beproud/django-newauth pull request #22
Opened 2022-02-14 00:16 UTC by cactusman-bp

メインの修正は、render_to_response メソッドと url メソッドの廃止に伴うリプレイス。

他は現時点で簡単に修正できる範囲での警告対応。

2022-02-14 00:29 UTC, shimizukawa requested changes
レビューしました

2022-02-14 00:29 UTC, shimizukawa commented on tests/testapp/urls.py
> +    re_path(r'^testapp/testapp_login_required', login_required(["testapp"])(testview)),
MUST: ここは `re_path` の必要ないので、pathにしてください
https://docs.djangoproject.com/ja/3.2/ref/urls/#path

2022-02-14 00:29 UTC, shimizukawa commented on newauth/admin.py
> +            re_path(r'^(.+)/password/$', self.admin_site.admin_view(self.user_change_password))
MUST: ここは re_path の必要はない
pathでslugを使ってください
https://docs.djangoproject.com/ja/3.2/ref/urls/#path

2022-08-03 08:35 UTC, bp-imaxyz commented on newauth/admin.py
> +            re_path(r'^(.+)/password/$', self.admin_site.admin_view(self.user_change_password))
BasicUserAdminの実装を参考に、pathでslugする実装に変更しました。

2022-08-03 08:37 UTC, imaxyz commented on newauth/admin.py
> +            re_path(r'^(.+)/password/$', self.admin_site.admin_view(self.user_change_password))
BasicUserAdminの処理を参考に、pathとslugを用いた実装に変更しました。

2022-08-03 08:56 UTC, imaxyz commented on newauth/admin.py
> +            re_path(r'^(.+)/password/$', self.admin_site.admin_view(self.user_change_password))
BasicUserAdminの実装を参考に、pathとslugを用いた実装に変更しました。

2022-08-03 08:57 UTC, imaxyz commented on tests/testapp/urls.py
> +    re_path(r'^testapp/testapp_login_required', login_required(["testapp"])(testview)),
pathを使用した実装に変更しました。

2022-08-03 09:01 UTC, imaxyz commented
申し訳ありません。bp-imaxyz という私の検証用のgithubユーザーでコミットしてしまったため、revertをしています。

- https://github.com/beproud/django-newauth/pull/22/commits/aa273ee78cb139f7507675dcf3ac16a92df06c5a
- https://github.com/beproud/django-newauth/pull/22/commits/388f7f2ebfccbab6c46e2dde3e2afcc3de9de2c7

2022-08-04 06:26 UTC, imaxyz commented on tests/testapp/urls.py
> +    re_path(r'^testapp/testapp_login_required', login_required(["testapp"])(testview)),
メモ:  PRの背景。 django.conf.urls.urlはDjango4で削除される。

```
def url(regex, view, kwargs=None, name=None):
    warnings.warn(
        'django.conf.urls.url() is deprecated in favor of '
        'django.urls.re_path().',
        RemovedInDjango40Warning,
        stacklevel=2,
    )
    return re_path(regex, view, kwargs, name)
```

https://github.com/django/django/blob/746e88cc634469112b823225c19d75c7362f8ecf/django/conf/urls/__init__.py#L15

2022-08-04 06:30 UTC, imaxyz commented on tests/testapp/urls.py
> +    re_path(r'^testapp/testapp_login_required', login_required(["testapp"])(testview)),
メモ: 'path' か 're_path' か というstack overflowのスレッド。

https://stackoverflow.com/questions/55285814/when-should-i-use-path-over-re-path

django.conf.urls.urlのリプレースにあたっては、

- 基本、django.urls.pathに置き換えた方が読み易そう
- 正規表現で書いた方が処理効率が良さそうなのでば、django.urls.re_pathに置き換えたらどうか
 
という意見と理解

2022-08-04 06:37 UTC, imaxyz commented on newauth/admin.py
> +from django.shortcuts import render, get_object_or_404
メモ: https://docs.djangoproject.com/en/2.2/topics/http/shortcuts/#render-to-response

2022-08-04 06:47 UTC, imaxyz commented on newauth/api.py
> +from django.utils.translation import gettext_lazy as _
メモ: https://github.com/django/django/blob/653a7bd7b7c2f7c3ffe6b22be53da1472c491474/django/utils/translation/__init__.py#L141

2022-08-04 06:48 UTC, imaxyz commented on newauth/api.py
> +        return force_str(self.pk)
メモ: https://github.com/django/django/blob/653a7bd7b7c2f7c3ffe6b22be53da1472c491474/django/utils/encoding.py#L112

2022-08-04 08:04 UTC, imaxyz commented on ChangeLog.rst
> Release 0.41 (2022-08-x)

レビュー完了後、日付はmasterにマージする日に変更します。

2022-08-05 01:06 UTC, cactusman-bp commented
LGTM

2022-08-06 14:04 UTC, shimizukawa requested changes
レビューしました。MUST 1つ、ASK 3つあります

2022-08-06 14:04 UTC, shimizukawa commented on newauth/admin.py
> +                name='auth_user_password_change'
ASK: このnameはどのシーンで使いますか？ 
使うのであればChangelogやドキュメントへ反映したほうがよいのでは？

2022-08-06 14:04 UTC, shimizukawa commented on tests/testapp/urls.py
> +    path('testapp/testapp_login_required/', login_required(["testapp"])(testview), name='testapp_login_required'),
ASK: 追加している `name=` は何のためですか？

2022-08-09 03:11 UTC, imaxyz commented on tests/test_api.py
> +        self.assertEqual(session_data.get('bn'), 'testapp3')
メモ: Djangoが使用するunittestでassertEquals()は非推奨なので、水晶のassertEqualに変更

https://docs.python.org/3/library/unittest.html#deprecated-aliases

2022-08-09 04:37 UTC, imaxyz commented on newauth/admin.py
> +                name='auth_user_password_change'
見直したところ、この箇所ではnameパラメータは必要ないと思いました。削除しました。

2022-08-09 04:40 UTC, imaxyz commented on tests/testapp/urls.py
> +    path('testapp/testapp_login_required/', login_required(["testapp"])(testview), name='testapp_login_required'),
見直したところ、この箇所のnameパラメータも追加の必要はないと思いました。削除しました。

2022-08-09 04:55 UTC, imaxyz commented on tests/testapp/urls.py
> +    path('account/logout/', views.logout, name='newauth_logout'),
実装当時、include()を使わない記述を思いつかなかったため、その書き方にしていました。

見直したところ、`path()` と `include('newauth.urls')` を両方使用して、より簡潔に書けそうなことがわかったので修正しました。

2022-08-09 04:59 UTC, imaxyz commented on newauth/admin.py
> +from django.urls import path
メモ: https://github.com/beproud/django-newauth/pull/22#discussion_r937392594

2022-08-09 05:13 UTC, imaxyz commented on ChangeLog.rst
> +- Fixed: Django-3.2 Support
ChangeLogの記述を具体的な修正内容に訂正しました。

2022-08-12 03:15 UTC, shimizukawa approved these changes
LGTM！！

2022-08-12 03:50 UTC, aodag commented on tests/testapp/urls.py
> +    path('testapp/testapp_login_required/', login_required(["testapp"])(testview)),
末尾 `/` が増えた理由がわかりにくいのでPR上で説明しておいたほうがよいと思います。

2022-08-16 03:31 UTC, imaxyz commented on tests/testapp/urls.py
> +    path('testapp/testapp_login_required/', login_required(["testapp"])(testview)),
> 末尾 / が増えた理由

```
path('testapp/testapp_login_required/', login_required(["testapp"])(testview))
```

この箇所のURLは、ディレクトリPathを指定している既存のユニットテストに応じるために必要でした。

https://github.com/beproud/django-newauth/blob/80ffb879cc7ccca39542aabd94e7c4f62a2070ed/tests/test_decorator.py#L23

また、今回から使用し始めたpath()メソッドの第1引数は、以下に示すシグニチャの `route` に相当し、URL文字列の入力が期待されているため、ファイルPathではなくディレクトリPathを表現するように、末尾に `/` を付加しました。

```
path( route , view , kwargs = None , name = None ) 
```

https://docs.djangoproject.com/en/3.2/ref/urls/#django.urls.path

2022-08-16 08:08 UTC, shimizukawa commented on tests/testapp/urls.py
> +    path('testapp/testapp_login_required/', login_required(["testapp"])(testview)),
はい。もっとシンプルに説明出来そうですが、説明内容はOKです。

私が説明するとしたら「末尾スラッシュ無しだとUnitTestでリクエストが404になりました（<CIのリンク>）。これはurl()からpath()にしたことでURL定義が正規表現による前方一致から、文字列による完全一致に変わったためです（<Djangoドキュメントのリンク>）」という主旨で書くと思います。

2022-08-16 08:17 UTC, merged