Django 4.2対応
beproud/django-newauth pull request #23
Opened 2023-09-15 03:43 UTC by cactusman-bp

2023-09-15 04:40 UTC, cactusman-bp commented on newauth/decorators.py
> +            path = quote(request.get_full_path())
urlquoteは4.0で廃止。

2023-09-15 04:40 UTC, cactusman-bp commented on newauth/signals.py
> +user_logged_in = Signal()
4.0でSignalのコンストラクタの引数に、providing_argsが廃止。

2023-09-15 04:40 UTC, cactusman-bp commented on newauth/signals.py
> +user_logged_out = Signal()
4.0でSignalのコンストラクタの引数に、providing_argsが廃止。

2023-09-15 04:40 UTC, cactusman-bp commented on newauth/test.py
> +            AuthMiddleware(get_response_empty).process_request(request)
4.0でMiddlewareのコンストラクタに、get_responseが必須に。
https://docs.djangoproject.com/en/4.2/topics/http/middleware/#writing-your-own-middleware

2023-09-15 04:40 UTC, cactusman-bp commented on newauth/test.py
> +    return HttpResponse()
テスト用のget_response関数。

2023-09-15 04:40 UTC, cactusman-bp commented on tests/test_api.py
> +        AuthMiddleware(get_response_empty).process_request(request)
4.0でMiddlewareのコンストラクタに、get_responseが必須に。
https://docs.djangoproject.com/en/4.2/topics/http/middleware/#writing-your-own-middleware

2023-09-15 04:40 UTC, cactusman-bp commented on tests/test_api.py
> +    return HttpResponse()
テスト用のget_response関数。

2023-09-15 04:40 UTC, cactusman-bp commented on tests/test_api.py
> +        AuthMiddleware(get_response_empty).process_request(request)
4.0でMiddlewareのコンストラクタに、get_responseが必須に。
https://docs.djangoproject.com/en/4.2/topics/http/middleware/#writing-your-own-middleware

2023-09-15 04:40 UTC, cactusman-bp commented on tests/test_middleware.py
> +        self.session_middleware = SessionMiddleware(get_response_empty)
4.0でMiddlewareのコンストラクタに、get_responseが必須に。
https://docs.djangoproject.com/en/4.2/topics/http/middleware/#writing-your-own-middleware

2023-09-15 04:40 UTC, cactusman-bp commented on tests/test_views.py
> +            self.assertFormError(response.context['form'], None, "Please enter a correct username and password. Note that both fields may be case-sensitive.")
5.0でassertFormError の第一引数がformオブジェクトに変更。

2023-09-15 04:40 UTC, cactusman-bp commented on tests/test_views.py
> +            self.assertFormError(response.context['form'], 'username', u'This field is required.')
5.0でassertFormError の第一引数がformオブジェクトに変更。

2023-09-15 04:40 UTC, cactusman-bp commented on tests/test_views.py
> +            self.assertFormError(response.context['form'], 'password', u'This field is required.')
5.0でassertFormError の第一引数がformオブジェクトに変更。

2023-09-15 04:40 UTC, cactusman-bp commented on tests/test_middleware.py
> +    return HttpResponse()
テスト用のget_response関数。

2023-09-18 21:21 UTC, shimizukawa approved these changes
LGTM with a MAY

2023-09-18 21:21 UTC, shimizukawa commented on .github/workflows/ci.yml
> +        django-version: ['3.2','4.2']
MAY: 4.1もテストされていると有り難いです。

```suggestion
        django-version: ['3.2','4.1','4.2']
```

3.2から4系に上げる場合、4.2ではMySQL5がサポート対象外になっていることから、一旦4.1に上げるケースがあります。このため、4.1もテストが通って居ると少し気が楽です。

toxでdj41を追加してテストしたところ、コード変更なしでテストは通りました。

2023-09-18 21:21 UTC, shimizukawa commented on setup.py
> +        'Framework :: Django :: 4.2',
setup.pyもdeprecateになりつつあるので、別PRでpyproject.toml移行を出しますね。

2023-09-18 21:30 UTC, shimizukawa requested changes
3.12 のテストを追加するなら、テストを通したいので、MUSTコメントを付けました

2023-09-18 21:30 UTC, shimizukawa commented on .github/workflows/ci.yml
> +        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
MUST: 3.12 は `-dev` が必要です。
https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#specifying-a-python-version

```suggestion
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12-dev']
```

最新は `3.12.0-rc.2` 
https://github.com/actions/python-versions/releases

2023-09-18 21:30 UTC, shimizukawa commented on .github/workflows/ci.yml
>      - uses: actions/checkout@v2
（あと3行下にコメントを付けたかった）

https://github.com/beproud/django-newauth/blob/7468f07c2c996e9e7dfc67d1d221e65c93e3eabe/.github/workflows/ci.yml#L27

`setup-python@v4` に上げて良さそう。
https://github.com/actions/setup-python

2023-09-18 21:44 UTC, shimizukawa commented on ChangeLog.rst
>  Release 0.42 (Unreleased)
`django.VERSION` を更新お願いします。
（前のリリース後に上げ忘れてそう）
https://github.com/beproud/django-newauth/blob/4ccb803f2150e509a6e36e53e43067bc0c255cf6/newauth/__init__.py#L1

2023-09-18 22:10 UTC, shimizukawa commented on .github/workflows/ci.yml
> +        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
https://github.com/beproud/django-newauth/pull/24 で `-dev` を指定してみたところ、テストが通りました。

2023-09-18 22:11 UTC, shimizukawa commented on setup.py
> +        'Framework :: Django :: 4.2',
`pyproject.toml` に移行する別PRを作成しました。
https://github.com/beproud/django-newauth/pull/24

2023-09-19 07:19 UTC, cactusman-bp commented on .github/workflows/ci.yml
> +        django-version: ['3.2', '4.1', '4.2']
レビュー反映

2023-09-19 07:19 UTC, cactusman-bp commented on .github/workflows/ci.yml
> +            python-version: '3.12-dev'
レビュー反映

2023-09-19 07:19 UTC, cactusman-bp commented on .github/workflows/ci.yml
> +    - uses: actions/checkout@v4
レビュー反映

2023-09-19 07:19 UTC, cactusman-bp commented on .github/workflows/ci.yml
> +      uses: actions/setup-python@v4
レビュー反映

2023-09-19 07:19 UTC, cactusman-bp commented on .github/workflows/ci.yml
> +      uses: actions/cache@v3
レビュー反映

2023-09-19 07:19 UTC, cactusman-bp commented on newauth/__init__.py
> +VERSION_INFO = (0, 42)
レビュー反映

2023-09-19 07:19 UTC, cactusman-bp commented on newauth/admin.py
> +from django.utils.translation import gettext_lazy as _
4.0からugettext_lazyが廃止され、gettext_lazyへ。

2023-09-19 07:19 UTC, cactusman-bp commented on newauth/models.py
> +        if model_name == 'default':
is比較だと警告が出ていたのを見つけたので。

2023-09-19 07:19 UTC, cactusman-bp commented on docs/en/source/forms.rst
> +    from django.utils.translation import gettext_lazy as _
4.0からugettext_lazyが廃止され、gettext_lazyへ。

2023-09-19 07:20 UTC, cactusman-bp commented on .github/workflows/ci.yml
>      - uses: actions/checkout@v2
レビュー反映しました。

2023-09-19 21:01 UTC, shimizukawa approved these changes
LGTM!

2023-09-20 07:09 UTC, merged